# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(298, 541)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(298, 541))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    border-width:1px;\n"
"    border-radius: 8pxpx;\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    backgrouund-color:rgb(90, 90, 90);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Container = QtWidgets.QFrame(self.centralwidget)
        self.Container.setStyleSheet("QFrame { \n"
"background-color: rgb(113, 219, 182);\n"
"border-radius: 15px;\n"
"}")
        self.Container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Container.setObjectName("Container")
        self.Container_layout = QtWidgets.QVBoxLayout(self.Container)
        self.Container_layout.setContentsMargins(0, 0, 0, 0)
        self.Container_layout.setSpacing(0)
        self.Container_layout.setObjectName("Container_layout")
        self.Header = QtWidgets.QFrame(self.Container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Header.sizePolicy().hasHeightForWidth())
        self.Header.setSizePolicy(sizePolicy)
        self.Header.setMaximumSize(QtCore.QSize(16777215, 35))
        self.Header.setStyleSheet("")
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Header)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.Header)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ExitWin = QtWidgets.QPushButton(self.frame)
        self.ExitWin.setGeometry(QtCore.QRect(10, 10, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExitWin.sizePolicy().hasHeightForWidth())
        self.ExitWin.setSizePolicy(sizePolicy)
        self.ExitWin.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.ExitWin.setFont(font)
        self.ExitWin.setStyleSheet("QPushButton{\n"
"    display:flex;\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background-color: rgb(255, 56, 0);\n"
"    color:rgb(249, 60, 0);\n"
"    justify-contents:center;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    color:rgb(255, 255, 255);\n"
"    background-color: rgb(193, 46, 0);\n"
"}\n"
"")
        self.ExitWin.setCheckable(False)
        self.ExitWin.setAutoDefault(False)
        self.ExitWin.setObjectName("ExitWin")
        self.MinimizeWin = QtWidgets.QPushButton(self.frame)
        self.MinimizeWin.setGeometry(QtCore.QRect(40, 10, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MinimizeWin.sizePolicy().hasHeightForWidth())
        self.MinimizeWin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Al Bayan")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.MinimizeWin.setFont(font)
        self.MinimizeWin.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background-color: rgb(255, 201, 3);\n"
"    color:rgb(255, 201, 3);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    color:rgb(255, 255, 255);\n"
"    background-color: rgb(221, 177, 0);\n"
"}\n"
"")
        self.MinimizeWin.setCheckable(False)
        self.MinimizeWin.setAutoDefault(False)
        self.MinimizeWin.setObjectName("MinimizeWin")
        self.MaximizeWin = QtWidgets.QPushButton(self.frame)
        self.MaximizeWin.setGeometry(QtCore.QRect(70, 10, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MaximizeWin.sizePolicy().hasHeightForWidth())
        self.MaximizeWin.setSizePolicy(sizePolicy)
        self.MaximizeWin.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.MaximizeWin.setFont(font)
        self.MaximizeWin.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background-color: rgb(55, 202, 65);\n"
"    color:rgb(55, 202, 65);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    color:rgb(255, 255, 255);\n"
"    background-color: rgb(58, 153, 14);\n"
"}\n"
"")
        self.MaximizeWin.setAutoDefault(False)
        self.MaximizeWin.setObjectName("MaximizeWin")
        self.horizontalLayout.addWidget(self.frame)
        self.Btns = QtWidgets.QFrame(self.Header)
        self.Btns.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(98)
        sizePolicy.setVerticalStretch(150)
        sizePolicy.setHeightForWidth(self.Btns.sizePolicy().hasHeightForWidth())
        self.Btns.setSizePolicy(sizePolicy)
        self.Btns.setMinimumSize(QtCore.QSize(0, 0))
        self.Btns.setMaximumSize(QtCore.QSize(100, 50))
        self.Btns.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Btns.setStyleSheet("")
        self.Btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Btns.setLineWidth(0)
        self.Btns.setObjectName("Btns")
        self.horizontalLayout.addWidget(self.Btns)
        self.Container_layout.addWidget(self.Header)
        self.frame_4 = QtWidgets.QFrame(self.Container)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 110))
        font = QtGui.QFont()
        font.setFamily("American Typewriter")
        font.setPointSize(15)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Screen = QtWidgets.QLabel(self.frame_4)
        self.Screen.setSizeIncrement(QtCore.QSize(4, 0))
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.Screen.setFont(font)
        self.Screen.setStyleSheet("QLabel{\n"
"border-radius:0px;\n"
"background-color:rrgb(123, 219, 179);\n"
"color:white;\n"
"}\n"
"")
        self.Screen.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Screen.setTextFormat(QtCore.Qt.RichText)
        self.Screen.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Screen.setWordWrap(False)
        self.Screen.setIndent(10)
        self.Screen.setObjectName("Screen")
        self.verticalLayout_3.addWidget(self.Screen)
        self.Container_layout.addWidget(self.frame_4)
        self.KeyPad = QtWidgets.QFrame(self.Container)
        self.KeyPad.setFrameShape(QtWidgets.QFrame.Box)
        self.KeyPad.setFrameShadow(QtWidgets.QFrame.Raised)
        self.KeyPad.setObjectName("KeyPad")
        self.gridLayout = QtWidgets.QGridLayout(self.KeyPad)
        self.gridLayout.setContentsMargins(-1, 0, -1, 12)
        self.gridLayout.setSpacing(25)
        self.gridLayout.setObjectName("gridLayout")
        self.key_9 = QtWidgets.QPushButton(self.KeyPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_9.sizePolicy().hasHeightForWidth())
        self.key_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.key_9.setFont(font)
        self.key_9.setStyleSheet("QPushButton{\n"
"    background-color:rgb(90, 172, 146);\n"
"    color: rgb(85, 85, 85);\n"
"    border-color: black;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(107, 190, 160);\n"
"}")
        self.key_9.setObjectName("key_9")
        self.gridLayout.addWidget(self.key_9, 1, 0, 1, 1)
        self.key_divide = QtWidgets.QPushButton(self.KeyPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_divide.sizePolicy().hasHeightForWidth())
        self.key_divide.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.key_divide.setFont(font)
        self.key_divide.setStyleSheet("QPushButton{\n"
"    background-color:rgb(191, 191, 191);\n"
"    color: rgb(85, 85, 85);\n"
"    border-width:1px;\n"
"    border-color: black;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(219, 219, 219);\n"
"}")
        self.key_divide.setObjectName("key_divide")
        self.gridLayout.addWidget(self.key_divide, 0, 3, 1, 1)
        self.key_6 = QtWidgets.QPushButton(self.KeyPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_6.sizePolicy().hasHeightForWidth())
        self.key_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.key_6.setFont(font)
        self.key_6.setStyleSheet("QPushButton{\n"
"    background-color:rgb(90, 172, 146);\n"
"    color: rgb(85, 85, 85);\n"
"    border-color: black;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(107, 190, 160);\n"
"}")
        self.key_6.setObjectName("key_6")
        self.gridLayout.addWidget(self.key_6, 2, 0, 1, 1)
        self.key_subtract = QtWidgets.QPushButton(self.KeyPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_subtract.sizePolicy().hasHeightForWidth())
        self.key_subtract.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.key_subtract.setFont(font)
        self.key_subtract.setStyleSheet("QPushButton{\n"
"    background-color:rgb(191, 191, 191);\n"
"    color: rgb(85, 85, 85);\n"
"    border-width:1px;\n"
"    border-color: black;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(219, 219, 219);\n"
"}")
        self.key_subtract.setObjectName("key_subtract")
        self.gridLayout.addWidget(self.key_subtract, 3, 3, 1, 1)
        self.key_negativeToggle = QtWidgets.QPushButton(self.KeyPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_negativeToggle.sizePolicy().hasHeightForWidth())
        self.key_negativeToggle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.key_negativeToggle.setFont(font)
        self.key_negativeToggle.setStyleSheet("QPushButton{\n"
"    background-color:rgb(191, 191, 191);\n"
"    color: rgb(85, 85, 85);\n"
"    border-width:1px;\n"
"    border-color: black;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(219, 219, 219);\n"
"}")
        self.key_negativeToggle.setObjectName("key_negativeToggle")
        self.gridLayout.addWidget(self.key_negativeToggle, 0, 1, 1, 1)
        self.key_4 = QtWidgets.QPushButton(self.KeyPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_4.sizePolicy().hasHeightForWidth())
        self.key_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.key_4.setFont(font)
        self.key_4.setStyleSheet("QPushButton{\n"
"    background-color:rgb(90, 172, 146);\n"
"    color: rgb(85, 85, 85);\n"
"    border-color: black;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(107, 190, 160);\n"
"}")
        self.key_4.setObjectName("key_4")
        self.gridLayout.addWidget(self.key_4, 2, 2, 1, 1)
        self.key_mulitpy = QtWidgets.QPushButton(self.KeyPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_mulitpy.sizePolicy().hasHeightForWidth())
        self.key_mulitpy.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.key_mulitpy.setFont(font)
        self.key_mulitpy.setStyleSheet("QPushButton{\n"
"    background-color:rgb(191, 191, 191);\n"
"    color: rgb(85, 85, 85);\n"
"    border-width:1px;\n"
"    border-color: black;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(219, 219, 219);\n"
"}")
        self.key_mulitpy.setObjectName("key_mulitpy")
        self.gridLayout.addWidget(self.key_mulitpy, 1, 3, 1, 1)
        self.key_clear = QtWidgets.QPushButton(self.KeyPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_clear.sizePolicy().hasHeightForWidth())
        self.key_clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.key_clear.setFont(font)
        self.key_clear.setStyleSheet("QPushButton{\n"
"    background-color:rgb(191, 191, 191);\n"
"    color: rgb(85, 85, 85);\n"
"    border-width:1px;\n"
"    border-color: black;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(219, 219, 219);\n"
"}")
        self.key_clear.setObjectName("key_clear")
        self.gridLayout.addWidget(self.key_clear, 0, 0, 1, 1)
        self.key_5 = QtWidgets.QPushButton(self.KeyPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_5.sizePolicy().hasHeightForWidth())
        self.key_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.key_5.setFont(font)
        self.key_5.setStyleSheet("QPushButton{\n"
"    background-color:rgb(90, 172, 146);\n"
"    color: rgb(85, 85, 85);\n"
"    border-color: black;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(107, 190, 160);\n"
"}")
        self.key_5.setObjectName("key_5")
        self.gridLayout.addWidget(self.key_5, 2, 1, 1, 1)
        self.key_8 = QtWidgets.QPushButton(self.KeyPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_8.sizePolicy().hasHeightForWidth())
        self.key_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.key_8.setFont(font)
        self.key_8.setStyleSheet("QPushButton{\n"
"    background-color:rgb(90, 172, 146);\n"
"    color: rgb(85, 85, 85);\n"
"    border-color: black;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(107, 190, 160);\n"
"}")
        self.key_8.setObjectName("key_8")
        self.gridLayout.addWidget(self.key_8, 1, 1, 1, 1)
        self.key_1 = QtWidgets.QPushButton(self.KeyPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_1.sizePolicy().hasHeightForWidth())
        self.key_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.key_1.setFont(font)
        self.key_1.setStyleSheet("QPushButton{\n"
"    background-color:rgb(90, 172, 146);\n"
"    color: rgb(85, 85, 85);\n"
"    border-color: black;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(107, 190, 160);\n"
"}")
        self.key_1.setObjectName("key_1")
        self.gridLayout.addWidget(self.key_1, 3, 2, 1, 1)
        self.key_2 = QtWidgets.QPushButton(self.KeyPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_2.sizePolicy().hasHeightForWidth())
        self.key_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.key_2.setFont(font)
        self.key_2.setStyleSheet("QPushButton{\n"
"    background-color:rgb(90, 172, 146);\n"
"    color: rgb(85, 85, 85);\n"
"    border-color: black;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(107, 190, 160);\n"
"}")
        self.key_2.setObjectName("key_2")
        self.gridLayout.addWidget(self.key_2, 3, 1, 1, 1)
        self.key_0 = QtWidgets.QPushButton(self.KeyPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_0.sizePolicy().hasHeightForWidth())
        self.key_0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.key_0.setFont(font)
        self.key_0.setAutoFillBackground(False)
        self.key_0.setStyleSheet("QPushButton{\n"
"    background-color:rgb(90, 172, 146);\n"
"    color: rgb(85, 85, 85);\n"
"    border-color: black;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(107, 190, 160);\n"
"}")
        self.key_0.setObjectName("key_0")
        self.gridLayout.addWidget(self.key_0, 4, 0, 1, 2)
        self.key_percentage = QtWidgets.QPushButton(self.KeyPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_percentage.sizePolicy().hasHeightForWidth())
        self.key_percentage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.key_percentage.setFont(font)
        self.key_percentage.setStyleSheet("QPushButton{\n"
"    background-color:rgb(191, 191, 191);\n"
"    color: rgb(85, 85, 85);\n"
"    border-width:1px;\n"
"    border-color: black;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(219, 219, 219);\n"
"}")
        self.key_percentage.setObjectName("key_percentage")
        self.gridLayout.addWidget(self.key_percentage, 0, 2, 1, 1)
        self.key_equals = QtWidgets.QPushButton(self.KeyPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_equals.sizePolicy().hasHeightForWidth())
        self.key_equals.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.key_equals.setFont(font)
        self.key_equals.setAutoFillBackground(False)
        self.key_equals.setStyleSheet("QPushButton{\n"
"    background-color:rgb(191, 191, 191);\n"
"    color: rgb(85, 85, 85);\n"
"    border-width:1px;\n"
"    border-color: black;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(219, 219, 219);\n"
"}")
        self.key_equals.setObjectName("key_equals")
        self.gridLayout.addWidget(self.key_equals, 4, 3, 1, 1)
        self.key_add = QtWidgets.QPushButton(self.KeyPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_add.sizePolicy().hasHeightForWidth())
        self.key_add.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.key_add.setFont(font)
        self.key_add.setStyleSheet("QPushButton{\n"
"    background-color:rgb(191, 191, 191);\n"
"    color: rgb(85, 85, 85);\n"
"    border-width:1px;\n"
"    border-color: black;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(219, 219, 219);\n"
"}")
        self.key_add.setObjectName("key_add")
        self.gridLayout.addWidget(self.key_add, 2, 3, 1, 1)
        self.key_3 = QtWidgets.QPushButton(self.KeyPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_3.sizePolicy().hasHeightForWidth())
        self.key_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.key_3.setFont(font)
        self.key_3.setStyleSheet("QPushButton{\n"
"    background-color:rgb(90, 172, 146);\n"
"    color: rgb(85, 85, 85);\n"
"    border-color: black;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(107, 190, 160);\n"
"}")
        self.key_3.setObjectName("key_3")
        self.gridLayout.addWidget(self.key_3, 3, 0, 1, 1)
        self.key_7 = QtWidgets.QPushButton(self.KeyPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_7.sizePolicy().hasHeightForWidth())
        self.key_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.key_7.setFont(font)
        self.key_7.setStyleSheet("QPushButton{\n"
"    background-color:rgb(90, 172, 146);\n"
"    color: rgb(85, 85, 85);\n"
"    border-color: black;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(107, 190, 160);\n"
"}")
        self.key_7.setObjectName("key_7")
        self.gridLayout.addWidget(self.key_7, 1, 2, 1, 1)
        self.key_decimal = QtWidgets.QPushButton(self.KeyPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_decimal.sizePolicy().hasHeightForWidth())
        self.key_decimal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.key_decimal.setFont(font)
        self.key_decimal.setStyleSheet("QPushButton{\n"
"    background-color:rgb(90, 172, 146);\n"
"    color: rgb(85, 85, 85);\n"
"    border-color: black;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(107, 190, 160);\n"
"}")
        self.key_decimal.setCheckable(False)
        self.key_decimal.setObjectName("key_decimal")
        self.gridLayout.addWidget(self.key_decimal, 4, 2, 1, 1)
        self.Container_layout.addWidget(self.KeyPad)
        self.verticalLayout.addWidget(self.Container)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ExitWin.setText(_translate("MainWindow", "x"))
        self.MinimizeWin.setText(_translate("MainWindow", "-"))
        self.MaximizeWin.setText(_translate("MainWindow", "+"))
        self.Screen.setText(_translate("MainWindow", "0"))
        self.key_9.setText(_translate("MainWindow", "9"))
        self.key_divide.setText(_translate("MainWindow", "÷"))
        self.key_6.setText(_translate("MainWindow", "6"))
        self.key_subtract.setText(_translate("MainWindow", "-"))
        self.key_negativeToggle.setText(_translate("MainWindow", "+/-"))
        self.key_4.setText(_translate("MainWindow", "4"))
        self.key_mulitpy.setText(_translate("MainWindow", "x"))
        self.key_clear.setText(_translate("MainWindow", "AC"))
        self.key_5.setText(_translate("MainWindow", "5"))
        self.key_8.setText(_translate("MainWindow", "8"))
        self.key_1.setText(_translate("MainWindow", "1"))
        self.key_2.setText(_translate("MainWindow", "2"))
        self.key_0.setText(_translate("MainWindow", "0"))
        self.key_percentage.setText(_translate("MainWindow", "%"))
        self.key_equals.setText(_translate("MainWindow", "="))
        self.key_add.setText(_translate("MainWindow", "+"))
        self.key_3.setText(_translate("MainWindow", "3"))
        self.key_7.setText(_translate("MainWindow", "7"))
        self.key_decimal.setText(_translate("MainWindow", "."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
